export ZSH="$HOME/.oh-my-zsh"
export PATH="/home/pedro/.local/bin:$PATH"
export EDITOR=nvim
#Create env var to access Download folder inside Windows
# See if works with SynLinc
export wd_folder=/mnt/c/Users/pedro/Downloads
export machine_config=~/Workspace/personal/machine_config
#Change escape key on zsh vim mode to jj
export ZVM_VI_INSERT_ESCAPE_BINDKEY=jj
ZSH_THEME="robbyrussell"

plugins=(git
    dnf
    zsh-syntax-highlighting
    zsh-autosuggestions
    asdf
    zsh-vi-mode
)

#STARTUPS SCRIPTS
source $ZSH/oh-my-zsh.sh
[ -f   /home/pedro/Workspace/personal/machine_config/utilities/kubectl_alias/.kubectl_aliases ] && source /home/pedro/Workspace/personal/machine_config/utilities/kubectl_alias/.kubectl_aliases

#PS1 CONFIGURATIONS
#PROMPT=$PROMPT'$(kube_ps1)'
#TMUX alias 
alias tmwk='cat /home/pedro/Workspace/personal/machine_config/utilities/tmwk/tmwk.txt | fzf'
alias tmnew='NEW_SESSION_NAME=$(basename $PWD); tmux new-session -t $NEW_SESSION_NAME'
alias tmadir='SESSION_NAME=$(basename $PWD); tmux a -t $SESSION_NAME'
alias tm=tmux
#Misc Alias
alias goto='DIR=$(zoxide query -l | fzf --reverse --print0) ; cd $DIR'

#Terraform alias
alias t='terraform'
alias tinit='terraform init'
alias tplan='terraform plan'
alias tapply='terraform apply'

#Terragrunt alias
alias tr='terragrunt'
alias trplan='terragrunt plan'
alias trapply='terragrunt apply'

#Kubectx Alias
alias kunset='kubectx --unset'

#zoxide

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(starship init zsh)"

eval "$(zoxide init zsh)"

zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

#export GOPATH=/home/pedro/workspace/go
